package sgf

const Annotator = "AN"
const Copyright = "CP"
const Date = "DT"
const Event = "EV"
const GameComment = "GC"
const Comment = "C"
const GameName = "GN"
const Handicap = "HA"
const Opening = "ON"
const Overtime = "OT"
const Place = "PC"
const PlayerBlackName = "PB"
const PlayerBlackRank = "BR"
const PlayerBlackTeam = "BT"
const PlayerWhiteName = "PW"
const PlayerWhiteRank = "WR"
const PlayerWhiteTeam = "WT"
const Result = "RE"
const Round = "RO"
const Rules = "RU"
const Source = "SO"
const TimeLimits = "TM"
const User = "US"
const Charset = "CA"
const Boardsize = "SZ"
const Komi = "KM"
